### ISSUE TITLE
About evaluation method

### ISSUE THREAD

**Issue by hellochick** [siliu-group/pic-challenge#1]
Hey,
I am curious about the evaluation procedure. Do you resize both prediction and ground truth into (640, 480) like `eval.py`?  I think it doesn't make sense to resize the ground truth.

Thank you a lot!

**Comment by Sundrops** [comment]
@hellochick Resizing is just for accelerating the evaluation while training. We'll keep their original size of prediction and ground when we eval your submission.

**Comment by hellochick** [comment]
Hey @Sundrops,

I have tried to run the provided `eval.py` and run on the demo data, but the results is really bad. That is, I got only 
```
0.08400 in IoU(0.25)
0.03400 in IoU(0.5)
0.00000 in IoU(0.75)
```
Is this accuracy correct? I think it might be much higher.
Thank you so much.

**Comment by Sundrops** [comment]
@hellochick 
It's right. This accuracy is a bit low since the result of pred just a demo. It's will be much higher if you trained model well.

**Comment by mahrukhawan** [comment]
@Sundrops  @hellochick I am unable  to access the annotations of the dataset, particularly the label annotations : Human Parts & Human Keypoints, Entity Segmentation annotations? If you have it downloaded somewhere, do let me know please.
